name: TheObjectiBits
favicon: null
layout_spectrum: 0.03881
typography_spectrum: 0.34057
title: The ObjectiBits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b9aad'
    - '#00000e'
    - '#29343f'
    - '#646464'
    - '#d7b578'
  brandStrength: 0.4375
  lightness: 0.9510748889297247
  saturation: 0.9328816507477313
  rhythmicContrast: 0.7190402434207499
purpose: []
